load 'build/debug/standarize_title.duckdb_extension';

create table job_titles (title text);

insert into job_titles (title) values
('software engineer'),
('product manager'),
('data scientist'),
('ux designer'),
('frontend developer'),
('backend developer'),
('devops engineer'),
('marketing manager'),
('hr specialist'),
('financial analyst'),
('content creator'),
('sales executive'),
('business analyst'),
('it consultant'),
('project manager'),
('quality assurance engineer'),
('graphic designer'),
('customer relations manager'),
('supply chain analyst'),
('digital strategist'),
('machine learning engineer'),
('cybersecurity analyst'),
('network administrator'),
('database administrator'),
('cloud architect'),
('game developer'),
('mobile app developer'),
('technical writer'),
('seo specialist'),
('social media manager'),
('event planner'),
('legal advisor'),
('operations manager'),
('research scientist'),
('biomedical engineer'),
('environmental consultant'),
('urban planner'),
('civil engineer'),
('mechanical engineer'),
('electrical engineer'),
('chemical engineer'),
('aerospace engineer'),
('architect'),
('interior designer'),
('fashion designer'),
('photographer'),
('videographer'),
('film director'),
('actor'),
('musician'),
('sound engineer'),
('teacher'),
('professor'),
('school counselor'),
('librarian'),
('nurse'),
('doctor'),
('pharmacist'),
('veterinarian'),
('physical therapist'),
('dietitian'),
('personal trainer'),
('chef'),
('baker'),
('restaurant manager'),
('hotel manager'),
('tour guide'),
('flight attendant'),
('pilot'),
('ship captain'),
('logistics coordinator'),
('warehouse manager'),
('construction manager'),
('real estate agent'),
('property manager'),
('insurance agent'),
('investment banker'),
('stock trader'),
('economist'),
('political analyst'),
('journalist'),
('editor'),
('translator'),
('interpreter'),
('software tester'),
('robotics engineer'),
('ai researcher'),
('blockchain developer'),
('quantitative analyst'),
('statistician'),
('actuary'),
('biologist'),
('chemist'),
('physicist'),
('astronomer'),
('geologist'),
('historian'),
('archaeologist'),
('anthropologist'),
('psychologist'),
('sociologist'),
('philosopher'),
('theologian'),
('author'),
('poet');

select title, standarize_title(title) from job_titles;